const awards = [
    { comp:"2025년 제15회 전국상업경진대회 세무실무", isPremier:true, name:"장인호", prize:"은상", year:2025, icon:"🏆" },
    { comp:"2025년 제15회 전국상업경진대회 비즈니스프로그래밍", isPremier:true, name:"양현욱", prize:"은상", year:2025, icon:"🏆" },
    { comp:"2025년 제15회 전국상업경진대회 금융실무", isPremier:true, name:"장연우", prize:"동상", year:2025, icon:"🏆" },
    { comp:"2025년 경기도 기능경기대회 피부미용", name:"심다은", prize:"장려상", year:2025, icon:"🏆" },
    { comp:"2025년 제25회 경기도상업교육페스티벌 금융실무", name:"장연우", prize:"은상", year:2025, icon:"🏆" },
    { comp:"2025년 제25회 경기도상업교육페스티벌 세무실무", name:"장인호", prize:"은상", year:2025, icon:"🏆" },
    { comp:"2025년 제25회 경기도상업교육페스티벌 비즈니스프로그래밍", name:"양현욱", prize:"장려상", year:2025, icon:"🏆" },
    { comp:"2025년 제25회 경기도상업교육페스티벌 컴퓨터그래픽", name:"김서현", prize:"동상", year:2025, icon:"🏆" },
    { comp:"2025년 제25회 경기도상업교육페스티벌 경제골든벨", name:"오예은", prize:"장려상", year:2025, icon:"🏆" },

    { comp:"2025학년도 대한민국 학생창의력 챔피언대회", name:"계예준, 김용훈, 이건일, 장주휘, 전준", prize:"동상", year:2025, icon:"💡" },
    { comp:"2025학년도 대한민국 학생창의력 챔피언대회", name:"김시연, 박현진, 오지선, 최소희, 최지수", prize:"동상", year:2025, icon:"💡" },
    { comp:"2025학년도 대한민국 학생창의력 챔피언대회", name:"박경윤, 이수하, 장은희, 하예나, 황지원", prize:"은상", year:2025, icon:"💡" },

    { comp:"제34회 경기도청소년연극제", name:"남하늘", prize:"동상", year:2025, icon:"🎭" },
    { comp:"제34회 경기도청소년연극제", name:"곽권", prize:"우수연기상", year:2025, icon:"🎭" },

    { comp:"제23회 월드뷰티아트 디자인 국제 공모전", isPremier:true, name:"안다솜", prize:"대상", year:2025, icon:"💅" },
    { comp:"제23회 월드뷰티아트 디자인 국제 공모전", isPremier:true, name:"김가온, 이유진, 이채빈", prize:"금상", year:2025, icon:"💅" },
    { comp:"제23회 월드뷰티아트 디자인 국제 공모전", isPremier:true, name:"심혜림, 유소영", prize:"은상", year:2025, icon:"💅" },
    { comp:"제23회 월드뷰티아트 디자인 국제 공모전", isPremier:true, name:"김유민", prize:"금상", year:2025, icon:"💅" },
    { comp:"제23회 월드뷰티아트 디자인 국제 공모전", isPremier:true, name:"김유민, 이채빈", prize:"은상", year:2025, icon:"💅" },
    { comp:"제23회 월드뷰티아트 디자인 국제 공모전", isPremier:true, name:"김서연, 장유정", prize:"동상", year:2025, icon:"💅" },

    { comp:"2025학년도 과정평가형 자격 미용사(일반)", 
    name:"김민서, 김보빈, 김시우, 김유민, 김주연, 심가현, 심다은, 심채영, 양은혜, 윤하연, 이세린, 이수아, 이예진, 이지혜, 이채빈, 장연지, 최민아, 최희정",
    prize:"합격", year:2025, icon:"✂️" },

    { comp:"2025학년도 과정평가형 정보처리산업기사", 
    name:"권0영, 김0경, 김0호, 박0우, 박0결, 양0석, 양0욱, 유0찬, 유0진, 이0영, 이0지, 이0한, 장0준, 전0준, 정0서, 최0람, 김0민, 김0우",
    prize:"합격", year:2025, icon:"💻" },
];

const jobs = [
    { company:"새마을금고", dept:"금융경영과", name:"권은비", type:"금융기관", emoji:"🏦" },
    { company:"해병대부사관(6월)", dept:"금융경영과", name:"최은학", type:"군(부사관)", emoji:"🪖" },
    { company:"해병대부사관(6월)", dept:"스마트웹콘텐츠과", name:"황인교", type:"군(부사관)", emoji:"🪖" },
    { company:"메이리츠증권", dept:"금융경영과", name:"오예은", type:"금융기관", emoji:"💹" },
    { company:"기술보증기금", dept:"회계정보과", name:"김지환", type:"공기업", emoji:"🏛️" },
    { company:"SOOP (구, 아프리카TV)", dept:"금융경영과", name:"이아랑", type:"민간기업", emoji:"📺" },
    { company:"육군부사관(7월)", dept:"창업마케팅과", name:"이성민", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"강동하", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"강소현", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"권유주", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"김동혁", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"김태빈", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"문소연", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"박미지", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"박유진", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"박지은", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"서희라", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"이준우", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"이지현", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"이지훈", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"이태민", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"임은수", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"장진우", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"조한희", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"최수빈", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"한예은", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"부사관과", name:"허지우", type:"군(부사관)", emoji:"🪖" },
    { company:"육군부사관(7월), 공군부사관(8월)", dept:"소프트웨어개발과", name:"김지민", type:"군(부사관)", emoji:"🪖" },
    { company:"한국농수산식품유통공사", dept:"회계정보과", name:"임형준", type:"공기업", emoji:"🏛️" },
    { company:"(주)제이비케이랩", dept:"금융경영과", name:"윤찬빈", type:"민간기업", emoji:"🔬" },
    { company:"(주)제이비케이랩", dept:"금융경영과", name:"이채령", type:"민간기업", emoji:"🔬" },
    { company:"(주)제이비케이랩", dept:"금융경영과", name:"장민주", type:"민간기업", emoji:"🔬" },
    { company:"공군부사관(8월)", dept:"부사관과", name:"김보화", type:"군(부사관)", emoji:"🪖" },
    { company:"공군부사관(8월)", dept:"부사관과", name:"허찬우", type:"군(부사관)", emoji:"🪖" },
    { company:"하나은행", dept:"금융경영과과", name:"오예은", type:"금융기관", emoji:"🏦" },
    { company:"하나은행", dept:"회계정보과", name:"김한울", type:"금융기관", emoji:"🏦" },
];

const doje = [
    { company:"하마랩", name:"박시우", year:2025, cohort:"도제8기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"투비스마트", name:"곽권, 이윤건", year:2025, cohort:"도제8기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"진인프라", name:"김규민, 권세준, 최해람", year:2025, cohort:"도제8기", dept:"소프트웨어개발과", status:"우량기업" },
    { company:"시스너", name:"양현욱, 김태호", year:2025, cohort:"도제8기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"이액티브", name:"이솔지, 이서영", year:2025, cohort:"도제8기", dept:"소프트웨어개발과", status:"우량기업" },
    { company:"유플러스시스템", name:"김성우, 유호진", year:2025, cohort:"도제8기", dept:"소프트웨어개발과", status:"우량기업" },
    { company:"아신아이", name:"박한결", year:2025, cohort:"도제8기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"메타씨티", name:"장성준, 이태한, 정인서", year:2025, cohort:"도제8기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"디엑스티", name:"김민성, 권동영", year:2025, cohort:"도제8기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"뉴베이스", name:"장연준, 양준석", year:2025, cohort:"도제8기", dept:"소프트웨어개발과", status:"우량기업" },
    { company:"아이아에스티", name:"김민후", year:2025, cohort:"도제8기", dept:"소프트웨어개발과", status:"도제기업" },

    { company:"모빌리오", dept: "소프트웨어개발과", name:"김준, 김태우, 이상혁", year:2024, cohort:"도제7기", status:"도제기업" },
    { company:"비욘드데이터", dept: "소프트웨어개발과", name:"우진호, 조준성, 최율, 한승규", year:2024, cohort:"도제7기", status:"도제기업" },
    { company:"시스너", dept: "소프트웨어개발과", name:"연주영, 이도훈", year:2024, cohort:"도제7기", status:"도제기업" },
    { company:"애니셀", dept: "소프트웨어개발과", name:"김민준, 이화준, 정은교, 최환", year:2024, cohort:"도제7기", status:"우량기업" },
    { company:"에스티엔인포텍", dept: "소프트웨어개발과", name:"박준호, 최문찬", year:2024, cohort:"도제7기", status:"우량기업" },
    { company:"우정하이텍", dept: "소프트웨어개발과", name:"배서준, 정아영", year:2024, cohort:"도제7기", status:"도제기업" },
    { company:"유플러스시스템", dept: "소프트웨어개발과", name:"강정묵, 김지호", year:2024, cohort:"도제7기", status:"도제기업" },
    { company:"투비스마트", dept: "소프트웨어개발과", name:"김현빈, 오진규", year:2024, cohort:"도제7기", status:"도제기업" },

    { company:"넷매니아", dept: "소프트웨어개발과", name:"김도윤, 장우진", year:2023, cohort:"도제6기", status:"도제기업" },
    { company:"모아소프트", dept: "소프트웨어개발과", name:"허성영, 허승", year:2023, cohort:"도제6기", status:"우량기업" },
    { company:"비디젠", dept: "소프트웨어개발과", name:"박승지", year:2023, cohort:"도제6기", status:"도제기업" },
    { company:"비젠트로", dept: "소프트웨어개발과", name:"김태한, 손태영, 이상준", year:2023, cohort:"도제6기", status:"우량기업" },
    { company:"세피스", dept: "소프트웨어개발과", name:"김지인, 박재현", year:2023, cohort:"도제6기", status:"도제기업" },
    { company:"소프트보울", dept: "소프트웨어개발과", name:"강주호, 정하은", year:2023, cohort:"도제6기", status:"도제기업" },
    { company:"소프트캠프", dept: "소프트웨어개발과", name:"박보현, 서에녹, 송주환, 홍대영", year:2023, cohort:"도제6기", status:"우량기업" },
    { company:"시큐레이어", dept: "소프트웨어개발과", name:"김유강, 김민석, 문시영, 박재우", year:2023, cohort:"도제6기", status:"우량기업" },
    { company:"에프아이솔루션", dept: "소프트웨어개발과", name:"민경석, 배성진", year:2023, cohort:"도제6기", status:"우량기업" },
    { company:"윈즈시스템", dept: "소프트웨어개발과", name:"강주훈", year:2023, cohort:"도제6기", status:"도제기업" },
    { company:"이액티브", dept: "소프트웨어개발과", name:"김용민, 정상윤", year:2023, cohort:"도제6기", status:"우량기업" },
    { company:"지우정보기술", dept: "소프트웨어개발과", name:"고준성, 주승곤", year:2023, cohort:"도제6기", status:"도제기업" },
    { company:"투비스마트", dept: "소프트웨어개발과", name:"안우림, 정한얼", year:2023, cohort:"도제6기", status:"도제기업" },

    { company:"넷아이디", dept: "소프트웨어개발과", name:"마희재", year:2022, cohort:"도제5기", status:"도제기업" },
    { company:"디에스티인터내셔날", dept: "소프트웨어개발과", name:"김예준", year:2022, cohort:"도제5기", status:"우량기업" },
    { company:"소프트보울", dept: "소프트웨어개발과", name:"박성민, 이영준", year:2022, cohort:"도제5기", status:"도제기업" },
    { company:"스마트콘", dept: "소프트웨어개발과", name:"김민규, 문재선, 정정희", year:2022, cohort:"도제5기", status:"도제기업" },
    { company:"씨아이테크", dept: "소프트웨어개발과", name:"강별, 양승우, 이수지", year:2022, cohort:"도제5기", status:"우량기업" },
    { company:"아침소프트", dept: "소프트웨어개발과", name:"김상원, 양수호", year:2022, cohort:"도제5기", status:"도제기업" },
    { company:"에프아이솔루션", dept: "소프트웨어개발과", name:"박찬희, 임성식", year:2022, cohort:"도제5기", status:"우량기업" },
    { company:"엠클라우독", dept: "소프트웨어개발과", name:"김영준", year:2022, cohort:"도제5기", status:"도제기업" },
    { company:"유아이네트웍스", dept: "소프트웨어개발과", name:"박진형, 유근영, 이승찬", year:2022, cohort:"도제5기", status:"도제기업" },
    { company:"이아이씨엔", dept: "소프트웨어개발과", name:"김정빈, 신현호", year:2022, cohort:"도제5기", status:"우량기업" },
    { company:"투비스마트", dept: "소프트웨어개발과", name:"구현우, 조홍근, 최승원", year:2022, cohort:"도제5기", status:"도제기업" },
    
    { company:"소프트퓨전", name:"허준영, 양희수", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"에스티엔웍스", name:"박우빈, 박동유", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"엔조이소프트", name:"이현, 김찬우", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"우량기업" },
    { company:"엠케어코리아", name:"유승주", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"웰데이타시스템", name:"박수정, 정태희, 서태응, 이준영", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"지우정보기술", name:"진현수, 구승현", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"투비스마트", name:"김찬희, 도서희", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"한길더블류아이티", name:"강기윤, 최민재", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"아이브이엠", name:"김성민, 장태우", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"네오위드넷", name:"김태경, 이연후", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"우량기업" },
    { company:"리드포인트시스템", name:"김다현, 안희찬", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"도제기업" },
    { company:"비디", name:"김연화, 이정민", year:2021, cohort:"도제4기", dept:"소프트웨어개발과", status:"우량기업" },

    { company:"소프트퓨전", dept: "소프트웨어개발과", name:"김건우, 노태원", year:2020, cohort:"도제3기", status:"도제기업" },
    { company:"아침소프트", dept: "소프트웨어개발과", name:"이재용, 한이수", year:2020, cohort:"도제3기", status:"우량기업" },
    { company:"엔조이소프트", dept: "소프트웨어개발과", name:"정용준, 최병준", year:2020, cohort:"도제3기", status:"우량기업" },
    { company:"와임", dept: "소프트웨어개발과", name:"박현우, 이주현", year:2020, cohort:"도제3기", status:"도제기업" },
    { company:"위드아이에스", dept: "소프트웨어개발과", name:"박시완, 이민우", year:2020, cohort:"도제3기", status:"도제기업" },
    { company:"이노알에스", dept: "소프트웨어개발과", name:"김건아, 한상옥", year:2020, cohort:"도제3기", status:"우량기업" },
    { company:"한길더블유아이티", dept: "소프트웨어개발과", name:"김재우, 정현진", year:2020, cohort:"도제3기", status:"도제기업" },
    { company:"이음시스템즈", dept: "소프트웨어개발과", name:"박세영, 왕윤아, 조웅빈", year:2020, cohort:"도제3기", status:"도제기업" },
    { company:"엠케어코리아", dept: "소프트웨어개발과", name:"이성진", year:2020, cohort:"도제3기", status:"도제기업" },
    { company:"웰데이타시스템", dept: "소프트웨어개발과", name:"박도현, 임현우, 최원영", year:2020, cohort:"도제3기", status:"도제기업" },
    { company:"지우정보기술", dept: "소프트웨어개발과", name:"이정주, 장민수", year:2020, cohort:"도제3기", status:"도제기업" },

    { company:"웰데이타시스템", name:"김성현, 김민지", year:2019, cohort:"도제2기", dept:"디지털정보과", status:"도제기업" },
    { company:"센스톤", name:"박균오, 방진현", year:2019, cohort:"도제2기", dept:"디지털정보과", status:"도제기업" },
    { company:"티앤디소프트", name:"신규성, 조병준", year:2019, cohort:"도제2기", dept:"디지털정보과", status:"도제기업" },
    { company:"서진인스텍", name:"박재형, 전동혁", year:2019, cohort:"도제2기", dept:"디지털정보과", status:"우량기업" },
    { company:"올리브헬스케어", name:"김동영, 이윤수", year:2019, cohort:"도제2기", dept:"디지털정보과", status:"도제기업" },
    { company:"제이알정보기술", name:"이다빈, 홍민기", year:2019, cohort:"도제2기", dept:"디지털정보과", status:"도제기업" },
    { company:"와임", name:"이채원, 전지민", year:2019, cohort:"도제2기", dept:"디지털정보과", status:"도제기업" },
    { company:"와이키키소프트", name:"이진용, 최동기", year:2019, cohort:"도제2기", dept:"디지털정보과", status:"도제기업" },

    { company:"기원테크", dept: "디지털정보과", name:"서규환, 임동주, 조성현", year:2018, cohort:"도제1기", status:"도제기업" },
    { company:"소프트퓨전", dept: "디지털정보과", name:"박현기, 안용찬, 이용진", year:2018, cohort:"도제1기", status:"도제기업" },
    { company:"스피맥스", dept: "디지털정보과", name:"박주영, 이정한, 정주환", year:2018, cohort:"도제1기", status:"도제기업" },
    { company:"아와소프트", dept: "디지털정보과", name:"박주희, 김건, 남상엽", year:2018, cohort:"도제1기", status:"도제기업" },
    { company:"아침소프트", dept: "디지털정보과", name:"강태민", year:2018, cohort:"도제1기", status:"도제기업" },
    { company:"애니콤정보통신", dept: "디지털정보과", name:"김동엽, 배성민, 조현준", year:2018, cohort:"도제1기", status:"우량기업" },
    { company:"우정하이텍", dept: "디지털정보과", name:"배동연, 최시온", year:2018, cohort:"도제1기", status:"도제기업" },
    { company:"웰데이타시스템", dept: "디지털정보과", name:"강찬, 김어진, 이민석", year:2018, cohort:"도제1기", status:"도제기업" },
    { company:"제이알정보기술", dept: "디지털정보과", name:"정기홍, 정용환", year:2018, cohort:"도제1기", status:"도제기업" },
];

const nco = [
    { company:"공군", dept:"부사관과", name:"강민지", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"공군", dept:"부사관과", name:"권해원", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"해군", dept:"부사관과", name:"김나정", cohort:"부사관과 5기", emoji:"⚓" },
    { company:"공군", dept:"부사관과", name:"김아영", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"공군", dept:"부사관과", name:"김예빈", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"육군", dept:"부사관과", name:"김은수", cohort:"부사관과 5기", emoji:"🪖" },
    { company:"공군", dept:"부사관과", name:"안수아", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"육군 특전사", dept:"부사관과", name:"안수용", cohort:"부사관과 5기", emoji:"🐺" },
    { company:"공군", dept:"부사관과", name:"안은빛", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"공군", dept:"부사관과", name:"우주찬", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"공군", dept:"부사관과", name:"이다은", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"육군 특전사", dept:"부사관과", name:"이현빈", cohort:"부사관과 5기", emoji:"🐺" },
    { company:"해병대", dept:"부사관과", name:"장경건", cohort:"부사관과 5기", emoji:"🪖" },
    { company:"육군", dept:"부사관과", name:"제정욱", cohort:"부사관과 5기", emoji:"🪖" },
    { company:"공군", dept:"부사관과", name:"최성준", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"공군", dept:"부사관과", name:"최재건", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"육군", dept:"부사관과", name:"최 훈", cohort:"부사관과 5기", emoji:"🪖" },
    { company:"공군", dept:"부사관과", name:"표승우", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"공군", dept:"부사관과", name:"홍민혁", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"공군", dept:"부사관과", name:"황영주", cohort:"부사관과 5기", emoji:"✈️" },
    { company:"공군", dept:"금융경영과", name:"이하나", cohort:"부사관 동아리 14기", emoji:"✈️" },
    { company:"육군 특전사", dept:"금융경영과", name:"강도현", cohort:"부사관 동아리 14기", emoji:"🐺" },
    { company:"육군 특전사", dept:"회계정보과", name:"김은혁", cohort:"부사관 동아리 14기", emoji:"🐺" },
    { company:"공군 제259특수임무대대(CCT)", dept:"회계정보과", name:"김민준", cohort:"부사관 동아리 14기", emoji:"🐺" },
    { company:"육군 특전사", dept:"회계정보과", name:"박찬석", cohort:"부사관 동아리 14기", emoji:"🐺" },
    { company:"제6탐색구조비행전대(SART)", dept:"창업마케팅과", name:"강나루", cohort:"부사관 동아리 14기", emoji:"🐺" },
    { company:"육군 특전사", dept:"창업마케팅과", name:"황주은", cohort:"부사관 동아리 14기", emoji:"🐺" },
    { company:"해군특수전전단(UDT)", dept:"스마트웹콘텐츠과", name:"김하늘", cohort:"부사관 동아리 14기", emoji:"🐺" },
    { company:"육군 특전사", dept:"스마트웹콘텐츠과", name:"노수정", cohort:"부사관 동아리 14기", emoji:"🐺" },
    { company:"육군 특전사", dept:"스마트웹콘텐츠과", name:"박진영", cohort:"부사관 동아리 14기", emoji:"🐺" },
    { company:"공군", dept:"스마트웹콘텐츠과", name:"정세빈", cohort:"부사관 동아리 14기", emoji:"✈️" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"강동하", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"강소현", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"권유주", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"김동혁", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"김보화", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"김태빈", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"문소연", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"박미지", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"박유진", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"박지은", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"서희라", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"이준우", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"이지현", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"이지훈", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"이태민", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"임은수", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"장진우", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"조한희", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"최수빈", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"한예은", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"부사관과", name:"허지우", cohort:"부사관과 6기", emoji:"🪖" },
    { company:"공군부사관", dept:"부사관과", name:"허찬우", cohort:"부사관과 6기", emoji:"✈️" },
    { company:"해병대부사관", dept:"금융경영과", name:"최은학", cohort:"부사관 동아리 15기", emoji:"🪖" },
    { company:"육군부사관", dept:"회계정보과", name:"이성민", cohort:"부사관 동아리 15기", emoji:"🪖" },
    { company:"해병대부사관", dept:"스마트웹콘텐츠과", name:"황인교", cohort:"부사관 동아리 15기", emoji:"🪖" },
    { company:"공군부사관・육군부사관", dept:"소프트웨어개발과", name:"김지민", cohort:"부사관 동아리 15기", emoji:"🪖" },
    { company:"707특수임무단", dept:"부사관과", name:"강인수", cohort:"부사관과 4기", emoji:"🐺" },
    { company:"해군특수전전단(UDT)", dept:"부사관과", name:"기영진", cohort:"부사관과 1기", emoji:"🐺" },
    { company:"해난구조전대(SSU)", dept:"부사관과", name:"강영재", cohort:"부사관과 1기", emoji:"🐺" },
    { company:"공군 제259특수임무대대(CCT)", dept:"부사관과", name:"김하언", cohort:"부사관과 1기", emoji:"🐺" },
    { company:"공군 제259특수임무대대(CCT)", dept:"회계정보과", name:"김민준", cohort:"부사관 동아리 14기", emoji:"🐺" },
    { company:"제6탐색구조비행전대(SART)", dept:"부사관과", name:"강민재", cohort:"부사관과 1기", emoji:"🐺" },
    { company:"제6탐색구조비행전대(SART)", dept:"부사관과", name:"안효근", cohort:"부사관과 1기", emoji:"🐺" },
    { company:"제6탐색구조비행전대(SART)", dept:"부사관과", name:"박민규", cohort:"부사관과 4기", emoji:"🐺" },
    { company:"제6탐색구조비행전대(SART)", dept:"부사관과", name:"박성훈", cohort:"부사관과 4기", emoji:"🐺" },
    { company:"제6탐색구조비행전대(SART)", dept:"창업마케팅과", name:"강나루", cohort:"부사관 동아리 14기", emoji:"🐺" },
];

const admissions = [
    // --- 4년제대학(주요대학: 강조) ---
    { category:"4년제대학", isPremier:true,  univ:"건국대학교", count:1, major:"정치외교과",         name:"최유경" },
    { category:"4년제대학", isPremier:true,  univ:"숭실대학교", count:1, major:"글로벌미디어학부",     name:"이원준" },
    { category:"4년제대학", isPremier:true,  univ:"아주대학교", count:1, major:"소프트웨어학과",       name:"손은규" },
    { category:"4년제대학", isPremier:true,  univ:"단국대학교", count:1, major:"경영학과",             name:"최유경" },
    { category:"4년제대학", isPremier:true,  univ:"서경대학교", count:1, major:"메이크업디자인과",     name:"박서아" },
    { category:"4년제대학", isPremier:true,  univ:"광운대학교", count:1, major:"소프트웨어학부",       name:"강서영" },

    // --- 4년제대학(일반) ---
    { category:"4년제대학", isPremier:false, univ:"명지대학교", count:1, major:"디지털미디어학부",     name:"이서아" },
    { category:"4년제대학", isPremier:false, univ:"상지대학교", count:1, major:"소프트웨어학과",       name:"최예나" },
    { category:"4년제대학", isPremier:false, univ:"을지대학교", count:1, major:"화장품과학전공",       name:"손은혜" },
    { category:"4년제대학", isPremier:false, univ:"을지대학교", count:1, major:"인문사회계열",         name:"박서아" },
    { category:"4년제대학", isPremier:false, univ:"을지대학교", count:1, major:"자연계열",             name:"변진화" },
    { category:"4년제대학", isPremier:false, univ:"평택대학교", count:1, major:"사회복지과",           name:"변하민" },
    { category:"4년제대학", isPremier:false, univ:"단국대학교(천안)", count:1, major:"해병대군사학과", name:"장경건" },
    { category:"4년제대학", isPremier:false, univ:"경동대학교", count:1, major:"간호학과",             name:"이아현" },
    { category:"4년제대학", isPremier:false, univ:"한국나사렛대학교", count:1, major:"태권도학과",   name:"유준상" },
    { category:"4년제대학", isPremier:false, univ:"동국대학교(듀이카)", count:1, major:"유아교육과", name:"김선림" },
    { category:"4년제대학", isPremier:false, univ:"동국대학교(경주)", count:1, major:"소방방제과",   name:"조한결" },
    { category:"4년제대학", isPremier:false, univ:"건국대학교(글로벌)", count:1, major:"패션디자인학과", name:"노은서" },

    // --- 선취업후진학 (상위권 대학은 강조) ---
    { category:"선취업후진학", isPremier:true,  univ:"국민대학교",   count:1, major:"기업융합법학과",       name:"박지나" },
    { category:"선취업후진학", isPremier:true,  univ:"홍익대학교",   count:1, major:"디자인예술경영학부",   name:"장수진" },
    { category:"선취업후진학", isPremier:true,  univ:"중앙대학교",   count:1, major:"지식경영학부",         name:"윤정희" },
    { category:"선취업후진학", isPremier:true,  univ:"홍익대학교",   count:1, major:"디자인예술경영학부",   name:"박한울" },
    { category:"선취업후진학", isPremier:true,  univ:"동국대학교",   count:1, major:"사회복지학과",         name:"문정연" },
    { category:"선취업후진학", isPremier:true,  univ:"홍익대학교",   count:1, major:"디자인예술경영학부",   name:"신유진" },
    { category:"선취업후진학", isPremier:true,  univ:"동국대학교",   count:1, major:"융합보안학과",         name:"서태풍" },
    { category:"선취업후진학", isPremier:true,  univ:"국민대학교",   count:1, major:"기업경영학부",         name:"김은희" },
    { category:"선취업후진학", isPremier:true,  univ:"경희대학교",   count:1, major:"국제통상금융투자학부", name:"허지원" },
    { category:"선취업후진학", isPremier:true,  univ:"숭실대학교",   count:1, major:"금융경제학과",         name:"전채원" },
    { category:"선취업후진학", isPremier:true,  univ:"한양대학교",   count:1, major:"산업융합학부",         name:"조승호" },
    { category:"선취업후진학", isPremier:true,  univ:"홍익대학교",   count:1, major:"디자인예술경영학부",   name:"송윤서" },
    { category:"선취업후진학", isPremier:true,  univ:"경희대학교",   count:1, major:"국제통상금융투자학부", name:"고아현" },
    { category:"선취업후진학", isPremier:true,  univ:"홍익대학교",   count:1, major:"디자인예술경영학부",   name:"김홍주" },
    { category:"선취업후진학", isPremier:true,  univ:"한양대학교",   count:1, major:"산업융합학부",         name:"이지예" },
    { category:"선취업후진학", isPremier:true,  univ:"한양대학교",   count:1, major:"산업융합학부",         name:"이동환" },
    { category:"선취업후진학", isPremier:true,  univ:"한양대학교",   count:1, major:"산업융합학부",         name:"한다현" },
    { category:"선취업후진학", isPremier:true,  univ:"한양대학교",   count:1, major:"산업융합학부",         name:"오홍걸" },
    { category:"선취업후진학", isPremier:false, univ:"명지대학교",   count:1, major:"부동산학과",           name:"이슬" },
    { category:"선취업후진학", isPremier:true,  univ:"한양대학교",   count:1, major:"산업융합학부",         name:"권태완" },
    { category:"선취업후진학", isPremier:true,  univ:"중앙대학교",   count:1, major:"지식경영학부",         name:"장윤지" },
    { category:"선취업후진학", isPremier:true,  univ:"숙명여자대학교", count:1, major:"",                   name:"박지원" },
    { category:"선취업후진학", isPremier:true,  univ:"한양대학교",   count:1, major:"산업융합학부",         name:"허지웅" },
    { category:"선취업후진학", isPremier:true,  univ:"한양대학교",   count:1, major:"산업융합학부",         name:"김수민" },
    { category:"선취업후진학", isPremier:true,  univ:"국민대학교",   count:1, major:"기업경영학부",         name:"김나영" },
    { category:"선취업후진학", isPremier:true,  univ:"한양대학교",   count:1, major:"산업경영학부",         name:"권희진" },
    { category:"선취업후진학", isPremier:true,  univ:"한양대학교",   count:1, major:"산업경영학부",         name:"박다사랑" },
    { category:"선취업후진학", isPremier:true,  univ:"경희대학교",   count:1, major:"국제통상학금융투자학과", name:"김서은" },
    { category:"선취업후진학", isPremier:true,  univ:"중앙대학교",   count:1, major:"지식경영학부",         name:"장한이" },
    { category:"선취업후진학", isPremier:true,  univ:"중앙대학교",   count:1, major:"지식경영학부",         name:"김연경" },
    
    // --- 전문대(집계형) ---
    { category:"전문대", isPremier:false, univ:"신구대학교",       count:22, major:"", name:"" },
    { category:"전문대", isPremier:false, univ:"동서울대학교",     count:15, major:"", name:"" },
    { category:"전문대", isPremier:false, univ:"폴리텍대학교",     count:9,  major:"", name:"" },
    { category:"전문대", isPremier:false, univ:"명지전문대학교",   count:4,  major:"", name:"" },
    { category:"전문대", isPremier:false, univ:"국제대학교",       count:1,  major:"", name:"" },
    { category:"전문대", isPremier:false, univ:"한양여대학교",     count:3,  major:"", name:"" },
    { category:"전문대", isPremier:false, univ:"연성대학교",       count:2,  major:"", name:"" },
    { category:"전문대", isPremier:false, univ:"그 외",           count:31, major:"", name:"" },

    // --- 대학(집계) ---
    { category:"2025졸업생", isPremier:true, univ:"건국대학교 외 10개 대학", count:11, major:"", name:"" },
    { category:"2025졸업생", isPremier:true, univ:"명지전문대학 외 18개 대학", count:56, major:"", name:"" },
    { category:"2024졸업생", isPremier:true, univ:"숭실대학교 외 10개 대학", count:12, major:"", name:"" },
    { category:"2024졸업생", isPremier:true, univ:"한양여자대학교 외 22개 대학", count:50, major:"", name:"" },
    { category:"2023졸업생", isPremier:true, univ:"이화여자대학교 외 12개 대학", count:14, major:"", name:"" },
    { category:"2023졸업생", isPremier:true, univ:"인하공업전문대학 외 23개 대학", count:56, major:"", name:"" },
    { category:"2022졸업생", isPremier:true, univ:"이화여자대학교 외 10개 대학", count:11, major:"", name:"" },
    { category:"2022졸업생", isPremier:true, univ:"ICT폴리텍대학 외 16개 대학", count:44, major:"", name:"" },
    { category:"2021졸업생", isPremier:true, univ:"단국대학교 외 6개 대학", count:9, major:"", name:"" },
    { category:"2021졸업생", isPremier:true, univ:"인하공업전문대학 외 15개 대학", count:41, major:"", name:"" },
    
    
];


const tickerTexts = {
    awards: [
    "👏 2025 각종 대회에서 다수 입상",
    "🥇 대상·금·은·동 수상 소식 꾸준히",
    "👍 성일정보고 학생 여러분 자랑스럽습니다!",
    "📣 자세한 내용은 학교 홈페이지 또는 학교로 문의 바랍니다"
    ],
    jobs: [
    "🎉 공기업·공단·대기업 취업 꾸준히 배출",
    "🪖 군(부사관) 진출자 다수",
    "🏦 금융기관 취업 소식",
    "📣 자세한 내용은 학교 홈페이지 또는 학교로 문의 바랍니다"
    ],
    doje: [
    "🤝 산학일체형 도제학교 운영(2017~)",
    "🏢 도제·우량기업 파트너십 확대",
    "👩‍💻 현장 중심 실무역량 강화",
    "📣 자세한 내용은 학교 홈페이지 또는 학교로 문의 바랍니다"
    ],
    nco: [
    "🪖 부사관·군 특수부대 진출 다수",
    "💪 체력·정신력을 겸비한 전문 부사관 양성",
    "🎯 707·UDT·CCT·SSU 등 특수부대 진출 성과",
    "📣 자세한 내용은 학교 홈페이지 또는 학교로 문의 바랍니다"
    ],
    admissions: [
    "🎓 4년제·전문대·선취업후진학 다양한 경로",
    "🌟 건국·아주·숭실·단국 등 주요대학 합격",
    "🔗 전공 연계·맞춤형 진학 상담 운영",
    "📣 자세한 내용은 학교 홈페이지 또는 학교로 문의 바랍니다"
    ],
};
