// NEIS API 설정
const NEIS_API_KEY = "86d5824114ac4902a87d57ce9146867d"; // 실제 발급받은 API 키를 여기에 넣으세요
const NEIS_OFFICE_CODE = "J10"; // 경기도교육청 코드
const NEIS_SCHOOL_CODE = "7530591"; // 성일정보고등학교 고유 코드

// 학생 등록 Firebase API 설정
const FIREBASE_STUREG_API_KEY = "AIzaSyAdfwOeE3nsi1zT2swvti7okFhCwdWyOhU";
const FIREBASE_STUREG_AUTH_DOMAIN = "lotterystudentdata.firebaseapp.com";
const FIREBASE_STUREG_PROJECT_ID = "lotterystudentdata";
const FIREBASE_STUREG_STORAGE_BUCKET = "lotterystudentdata.appspot.com";
const FIREBASE_STUREG_MESSAGING_SENDER_ID = "648117771294";
const FIREBASE_STUREG_APP_ID = "1:648117771294:web:c1e75d01221ad52168a20f";
const FIREBASE_STUREG_MEASUREMENT_ID = "G-R08W4VWPCN"; // 선택 사항

export {
    NEIS_API_KEY,
    NEIS_OFFICE_CODE,
    NEIS_SCHOOL_CODE,
    FIREBASE_STUREG_API_KEY,
    FIREBASE_STUREG_AUTH_DOMAIN,
    FIREBASE_STUREG_PROJECT_ID,
    FIREBASE_STUREG_STORAGE_BUCKET,
    FIREBASE_STUREG_MESSAGING_SENDER_ID,
    FIREBASE_STUREG_APP_ID,
    FIREBASE_STUREG_MEASUREMENT_ID
};